### ISSUE TITLE
useProfile

### ISSUE THREAD

**Issue by wds4** [t4t5/nostr-react#5]
useProfile works for me, ty for adding that 👍 

I'm glad you added batching. I've been having trouble with my feeds, probably bc of doing multiple individual user info requests and most get dropped.

Small issue with the useProfile example in README - I've opened a [pull request](https://github.com/t4t5/nostr-react/pull/4#issue-1516691362) to suggest a fix.

**Comment by t4t5** [comment]
Merged 🤝
