### ISSUE TITLE
Consider adding GitHub topics to this repo?

### ISSUE THREAD

**Issue by chmac** [t4t5/nostr-react#6]
Firstly, thanks a lot for releasing this library. It looks like exactly what I was about to start hacking. You've saved me a ton of work. 🧡 

I just discovered this repo through an awesome-nostr link from a ddg search. I had previously been through all the projects with the topic `nostr` on them. What about adding the `nostr`, `react` and may some other topics to this repo?

**Comment by t4t5** [comment]
Thank you for the suggestion! I've added `nostr` and `react` as topics for the repo now 🤝
